`timescale 1ns / 1ps
// instruction_memory.v
// NOP inserted at addr 6 to resolve STORE->LOAD hazard
//
// Execution trace:
// addr 0-3  : NOP padding
// addr 4    : MOV ACC, R1       ACC = 2
// addr 5    : STORE [15], ACC   mem[15] = 2
// addr 6    : NOP               hazard buffer
// addr 7    : MOV ACC, R3       ACC = 4
// addr 8    : LOAD [15]         ACC = mem[15] = 2
// addr 9    : ADD R2            ACC = 2+3 = 5
// addr 10   : BRANCH 13
// addr 11   : XOR R1            skipped
// addr 12   : HLT               skipped
// addr 13   : ADD R3            ACC = 5+4 = 9
// addr 14   : STORE [14], ACC   mem[14] = 9
// addr 15   : HLT

module instruction_memory (
    input  wire [3:0] addr,
    output reg  [7:0] data
);
    reg [7:0] memory [0:15];

    // Auto-generated by assembler.py
    initial begin
        memory[ 0] = 8'b00000000; // 0x00
        memory[ 1] = 8'b00000000; // 0x00
        memory[ 2] = 8'b00000000; // 0x00
        memory[ 3] = 8'b00000000; // 0x00
        memory[ 4] = 8'b10010001; // 0x91
        memory[ 5] = 8'b11101111; // 0xef
        memory[ 6] = 8'b00000000; // 0x00
        memory[ 7] = 8'b10010011; // 0x93
        memory[ 8] = 8'b11011111; // 0xdf
        memory[ 9] = 8'b00010010; // 0x12
        memory[10] = 8'b11001101; // 0xcd
        memory[11] = 8'b01100001; // 0x61
        memory[12] = 8'b11111111; // 0xff
        memory[13] = 8'b00010011; // 0x13
        memory[14] = 8'b11101110; // 0xee
        memory[15] = 8'b11111111; // 0xff
    end
    always @(*) begin
        data = memory[addr];
    end

endmodule