// Auto-generated by assembler.py
// Paste this initial block into instruction_memory.v

initial begin
    memory[ 0] = 8'b00000000; // 0x00
    memory[ 1] = 8'b00000000; // 0x00
    memory[ 2] = 8'b00000000; // 0x00
    memory[ 3] = 8'b00000000; // 0x00
    memory[ 4] = 8'b10010001; // 0x91
    memory[ 5] = 8'b11101111; // 0xef
    memory[ 6] = 8'b00000000; // 0x00
    memory[ 7] = 8'b10010011; // 0x93
    memory[ 8] = 8'b11011111; // 0xdf
    memory[ 9] = 8'b00010010; // 0x12
    memory[10] = 8'b11001101; // 0xcd
    memory[11] = 8'b01100001; // 0x61
    memory[12] = 8'b11111111; // 0xff
    memory[13] = 8'b00010011; // 0x13
    memory[14] = 8'b11101110; // 0xee
    memory[15] = 8'b11111111; // 0xff
end