#!/usr/bin/env python3
"""
assembler.py -- Custom Processor V2 Assembler
Converts assembly mnemonics into 8-bit machine code hex.

ISA encoding:
  NOP              0000_0000
  LSL              0000_0001
  LSR              0000_0010
  CIR              0000_0011
  CIL              0000_0100
  ASR              0000_0101
  INC              0000_0110
  DEC              0000_0111
  ADD  Rn          0001_rrrr
  SUB  Rn          0010_rrrr
  MUL  Rn          0011_rrrr
  AND  Rn          0101_rrrr
  XOR  Rn          0110_rrrr
  CMP  Rn          0111_rrrr
  MOV  ACC, Rn     1001_rrrr
  MOV  Rn, ACC     1010_rrrr
  RET              1011_0000
  BRANCH addr      1100_aaaa
  LOAD addr        1101_aaaa
  STORE addr, ACC  1110_aaaa
  HLT              1111_1111
"""

import sys
import os

# ?? Opcode table ?????????????????????????????????????????
OPCODES = {
    "NOP"    : 0b00000000,
    "LSL"    : 0b00000001,
    "LSR"    : 0b00000010,
    "CIR"    : 0b00000011,
    "CIL"    : 0b00000100,
    "ASR"    : 0b00000101,
    "INC"    : 0b00000110,
    "DEC"    : 0b00000111,
    "RET"    : 0b10110000,
    "HLT"    : 0b11111111,
}

# instructions that take a register operand Rn
REG_OPS = {
    "ADD"    : 0b00010000,
    "SUB"    : 0b00100000,
    "MUL"    : 0b00110000,
    "AND"    : 0b01010000,
    "XOR"    : 0b01100000,
    "CMP"    : 0b01110000,
}

# instructions that take an address operand
ADDR_OPS = {
    "BRANCH" : 0b11000000,
    "LOAD"   : 0b11010000,
    "STORE"  : 0b11100000,
}

def parse_register(token):
    """Parse R0-R15 and return register number."""
    token = token.strip().upper().rstrip(",")
    if not token.startswith("R"):
        raise ValueError(f"Expected register, got: {token}")
    num = int(token[1:])
    if num < 0 or num > 15:
        raise ValueError(f"Register out of range: {token}")
    return num

def parse_address(token):
    """Parse a 4-bit address (0-15)."""
    token = token.strip().rstrip(",")
    addr = int(token)
    if addr < 0 or addr > 15:
        raise ValueError(f"Address out of range: {addr}")
    return addr

def assemble_line(line, line_num):
    """
    Assemble one line of assembly into an 8-bit integer.
    Returns None for empty lines and comments.
    """
    # strip comments and whitespace
    line = line.split(";")[0].strip()
    line = line.split("#")[0].strip()
    if not line:
        return None

    tokens = line.upper().split()
    mnemonic = tokens[0]

    # ?? No-operand instructions ???????????????????????????
    if mnemonic in OPCODES:
        return OPCODES[mnemonic]

    # ?? Register operand instructions ?????????????????????
    if mnemonic in REG_OPS:
        if len(tokens) < 2:
            raise ValueError(f"Line {line_num}: {mnemonic} needs a register")
        reg = parse_register(tokens[1])
        return REG_OPS[mnemonic] | reg

    # ?? Address operand instructions ??????????????????????
    if mnemonic in ADDR_OPS:
        if len(tokens) < 2:
            raise ValueError(f"Line {line_num}: {mnemonic} needs an address")
        addr = parse_address(tokens[1])
        return ADDR_OPS[mnemonic] | addr

    # ?? MOV ACC, Rn ???????????????????????????????????????
    if mnemonic == "MOV":
        if len(tokens) < 3:
            raise ValueError(f"Line {line_num}: MOV needs two operands")
        dest = tokens[1].rstrip(",")
        src  = tokens[2].rstrip(",")
        if dest == "ACC":
            reg = parse_register(src)
            return 0b10010000 | reg   # MOV ACC, Rn
        else:
            reg = parse_register(dest)
            return 0b10100000 | reg   # MOV Rn, ACC

    raise ValueError(f"Line {line_num}: Unknown mnemonic '{mnemonic}'")

def assemble(source_text):
    """Assemble full source text, return list of (addr, byte) tuples."""
    instructions = []
    addr = 0
    for line_num, line in enumerate(source_text.splitlines(), 1):
        result = assemble_line(line, line_num)
        if result is not None:
            if addr > 15:
                raise ValueError(f"Line {line_num}: program exceeds 16 instructions")
            instructions.append((addr, result))
            addr += 1
    return instructions

def generate_verilog(instructions, output_path):
    """Generate a Verilog initial block for instruction_memory.v"""
    lines = []
    lines.append("// Auto-generated by assembler.py")
    lines.append("// Paste this initial block into instruction_memory.v")
    lines.append("")
    lines.append("initial begin")

    # fill all 16 with NOP first
    mem = [0] * 16
    for addr, byte in instructions:
        mem[addr] = byte

    for i, byte in enumerate(mem):
        lines.append(f"    memory[{i:2d}] = 8'b{byte:08b}; // {byte:#04x}")

    lines.append("end")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Verilog output written to: {output_path}")

def generate_hex(instructions, output_path):
    """Generate plain hex file, one byte per line."""
    mem = [0] * 16
    for addr, byte in instructions:
        mem[addr] = byte
    with open(output_path, "w") as f:
        for byte in mem:
            f.write(f"{byte:02X}\n")
    print(f"Hex output written to: {output_path}")

def print_listing(instructions):
    """Print human-readable listing to console."""
    print("")
    print(f"{'Addr':>4}  {'Hex':>4}  {'Binary':>10}  Instruction")
    print("-" * 50)
    for addr, byte in instructions:
        print(f"  {addr:2d}    {byte:#04x}  {byte:08b}")
    print("")
    print(f"Total instructions: {len(instructions)}")
    print("")

if __name__ == "__main__":
    # default: assemble the built-in test program
    test_program = """
; Custom Processor V2 -- test program
; Matches instruction_memory.v exactly
NOP
NOP
NOP
NOP
MOV ACC, R1     ; ACC = R1 = 2
STORE 15        ; mem[15] = 2
NOP             ; hazard buffer
MOV ACC, R3     ; ACC = R3 = 4
LOAD 15         ; ACC = mem[15] = 2
ADD R2          ; ACC = 2 + 3 = 5
BRANCH 13       ; jump to addr 13
XOR R1          ; skipped
HLT             ; skipped
ADD R3          ; ACC = 5 + 4 = 9
STORE 14        ; mem[14] = 9
HLT
"""

    if len(sys.argv) > 1:
        # read from file if provided
        with open(sys.argv[1]) as f:
            source = f.read()
    else:
        source = test_program
        print("No input file specified -- assembling built-in test program.")
        print("Usage: python assembler.py <program.asm>")

    try:
        instructions = assemble(source)
        print_listing(instructions)

        out_dir = os.path.dirname(os.path.abspath(__file__))
        generate_verilog(instructions,
            os.path.join(out_dir, "assembled_memory.v"))
        generate_hex(instructions,
            os.path.join(out_dir, "assembled_memory.hex"))

    except ValueError as e:
        print(f"Assembly error: {e}")
        sys.exit(1)
